# Problem Statement

A leading retail company wants to better understand its customers' shopping behavior in order to improve sales, customer satisfaction, and long term loyalty. The management team has seen some changes in the purchasing patterns accross demographics, product categories, and sales channel (online vs offline).They are puticularlu interested in uncovering various factors, such as discounts, reviews, seasons, or payment preferences, drive consumer decision and repeat purchases.

You are tasked with analyzing the company's consumer behavior dataset to answer the following overarching business question:

"How can the company leverage the consumer shopping data to identify trends, improve customer engagement, and optimize marketing and product strategies?"

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("shopping_behavior_updated.csv")

In [9]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [10]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [12]:
# summary statistics
# for both numerical and categorical data

df.describe(include = "all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

### find the null values in all the columns

df.isnull().sum()

In [14]:
# checking if Null, NaN, 0 are present in the cell in string format or not in rating review column 
# not possible because datatype of column is float64

df["Review Rating"].unique()

array([3.1, 3.5, 2.7, 2.9, 3.2, 2.6, 4.8, 4.1, 4.9, 4.5, 4.7, 2.8, 4.6,
       3.3, 4.4, 3.6, 5. , 4. , 3.7, 4.2, 3.9, 3. , 3.8, 3.4, 4.3, 2.5])

In [15]:
# finding Null, NaNn 0, - or any other problematic values in Age column

df["Age"].unique()

array([55, 19, 50, 21, 45, 46, 63, 27, 26, 57, 53, 30, 61, 65, 64, 25, 52,
       66, 31, 56, 18, 38, 54, 33, 36, 35, 29, 70, 69, 67, 20, 39, 42, 68,
       49, 59, 47, 40, 41, 48, 22, 24, 44, 37, 58, 32, 62, 51, 28, 43, 34,
       23, 60], dtype=int64)

In [16]:
# finding unnatural values in Gender

df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [17]:
df["Item Purchased"].unique()

array(['Blouse', 'Sweater', 'Jeans', 'Sandals', 'Sneakers', 'Shirt',
       'Shorts', 'Coat', 'Handbag', 'Shoes', 'Dress', 'Skirt',
       'Sunglasses', 'Pants', 'Jacket', 'Hoodie', 'Jewelry', 'T-shirt',
       'Scarf', 'Hat', 'Socks', 'Backpack', 'Belt', 'Boots', 'Gloves'],
      dtype=object)

In [18]:
df["Category"].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [19]:
df["Purchase Amount (USD)"].unique()

array([ 53,  64,  73,  90,  49,  20,  85,  34,  97,  31,  68,  72,  51,
        81,  36,  38,  48,  62,  37,  88,  22,  25,  56,  94,  79,  67,
        91,  33,  69,  45,  60,  76,  39, 100,  21,  43,  54,  55,  30,
        28,  59,  24,  83,  46,  70,  29,  26,  58,  96,  40,  32,  95,
        41,  47,  99,  87,  92,  98,  89,  35,  75,  65,  86,  84,  77,
        27,  23,  74,  80,  42,  61,  82,  78,  93,  50,  57,  66,  44,
        52,  71,  63], dtype=int64)

In [20]:
df["Location"].unique()

array(['Kentucky', 'Maine', 'Massachusetts', 'Rhode Island', 'Oregon',
       'Wyoming', 'Montana', 'Louisiana', 'West Virginia', 'Missouri',
       'Arkansas', 'Hawaii', 'Delaware', 'New Hampshire', 'New York',
       'Alabama', 'Mississippi', 'North Carolina', 'California',
       'Oklahoma', 'Florida', 'Texas', 'Nevada', 'Kansas', 'Colorado',
       'North Dakota', 'Illinois', 'Indiana', 'Arizona', 'Alaska',
       'Tennessee', 'Ohio', 'New Jersey', 'Maryland', 'Vermont',
       'New Mexico', 'South Carolina', 'Idaho', 'Pennsylvania',
       'Connecticut', 'Utah', 'Virginia', 'Georgia', 'Nebraska', 'Iowa',
       'South Dakota', 'Minnesota', 'Washington', 'Wisconsin', 'Michigan'],
      dtype=object)

In [21]:
for i in df.columns:
    print(df[i].unique())
    print()
    print("-"*50)
    print()

[   1    2    3 ... 3898 3899 3900]

--------------------------------------------------

[55 19 50 21 45 46 63 27 26 57 53 30 61 65 64 25 52 66 31 56 18 38 54 33
 36 35 29 70 69 67 20 39 42 68 49 59 47 40 41 48 22 24 44 37 58 32 62 51
 28 43 34 23 60]

--------------------------------------------------

['Male' 'Female']

--------------------------------------------------

['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes' 'Dress' 'Skirt' 'Sunglasses' 'Pants' 'Jacket' 'Hoodie'
 'Jewelry' 'T-shirt' 'Scarf' 'Hat' 'Socks' 'Backpack' 'Belt' 'Boots'
 'Gloves']

--------------------------------------------------

['Clothing' 'Footwear' 'Outerwear' 'Accessories']

--------------------------------------------------

[ 53  64  73  90  49  20  85  34  97  31  68  72  51  81  36  38  48  62
  37  88  22  25  56  94  79  67  91  33  69  45  60  76  39 100  21  43
  54  55  30  28  59  24  83  46  70  29  26  58  96  40  32  95  41  47
  99  87  92  98  89  35  75  65  86  84  77  27  23  74  80  42  61  82
  78  93  50  57  66  44  52  71  63]

--------------------------------------------------

['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri' 'Arkansas' 'Hawaii'
 'Delaware' 'New Hampshire' 'New York' 'Alabama' 'Mississippi'
 'North Carolina' 'California' 'Oklahoma' 'Florida' 'Texas' 'Nevada'
 'Kansas' 'Colorado' 'North Dakota' 'Illinois' 'Indiana' 'Arizona'
 'Alaska' 'Tennessee' 'Ohio' 'New Jersey' 'Maryland' 'Vermont'
 'New Mexico' 'South Carolina' 'Idaho' 'Pennsylvania' 'Connecticut' 'Utah'
 'Virginia' 'Georgia' 'Nebraska' 'Iowa' 'South Dakota' 'Minnesota'
 'Washington' 'Wisconsin' 'Michigan']

--------------------------------------------------

['L' 'S' 'M' 'XL']

--------------------------------------------------

['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold' 'Violet' 'Teal' 'Lavender' 'Black' 'Green' 'Peach' 'Red'
 'Cyan' 'Brown' 'Beige' 'Orange' 'Indigo' 'Yellow' 'Magenta' 'Blue']

--------------------------------------------------

['Winter' 'Spring' 'Summer' 'Fall']

--------------------------------------------------

[3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5 4.7 2.8 4.6 3.3 4.4 3.6 5.  4.
 3.7 4.2 3.9 3.  3.8 3.4 4.3 2.5]

--------------------------------------------------

['Yes' 'No']

--------------------------------------------------

['Express' 'Free Shipping' 'Next Day Air' 'Standard' '2-Day Shipping'
 'Store Pickup']

--------------------------------------------------

['Yes' 'No']

--------------------------------------------------

['Yes' 'No']

--------------------------------------------------

[14  2 23 49 31 19  8  4 26 10 37 34 44 36 17 46 50 22 32 40 16 13  7 41
 45 38 48 18 15 25 39 35 29 21 43  3  5 24 42 47 28 20 33  1  9 12 27 11
 30  6]

--------------------------------------------------

['Venmo' 'Cash' 'Credit Card' 'PayPal' 'Bank Transfer' 'Debit Card']

--------------------------------------------------

['Fortnightly' 'Weekly' 'Annually' 'Quarterly' 'Bi-Weekly' 'Monthly'
 'Every 3 Months']

--------------------------------------------------

In [22]:
# I do not see much of a problem here

In [23]:
# changing the columns names to snake format.
# everything will be lowercase and space will be replaced with _

df.columns = df.columns.str.lower() # converting evry capital letter to small letter
df.columns = df.columns.str.replace(" ","_") # replacing every space with underscore

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [25]:
# still there issue with purchase_amount_(usd)
# we will simply rename that 

df = df.rename(columns = {"purchase_amount_(usd)":"purchase_amount"})

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [27]:
# we are going to group customers into age groups "young adult", "adult", "middle age", "senior"

# concept of binning
bins = [18,25,45,60,120]
labels = ["young adult", "adult", "middle age", "senior"]

df["age_group"] = pd.cut(df["age"], bins = bins, labels = labels)

In [28]:
df["age_group"]

0        middle age
1       young adult
2        middle age
3       young adult
4             adult
           ...
3895          adult
3896     middle age
3897     middle age
3898          adult
3899     middle age
Name: age_group, Length: 3900, dtype: category
Categories (4, object): ['young adult' < 'adult' < 'middle age' < 'senior']

In [29]:
df["age_group"].unique()

['middle age', 'young adult', 'adult', 'senior', NaN]
Categories (4, object): ['young adult' < 'adult' < 'middle age' < 'senior']

In [30]:
df[["age","age_group"]]

      age    age_group
0      55   middle age
1      19  young adult
2      50   middle age
3      21  young adult
4      45        adult
...   ...          ...
3895   40        adult
3896   52   middle age
3897   46   middle age
3898   44        adult
3899   52   middle age

[3900 rows x 2 columns]

In [31]:
# creating purchase_frequency_days
# we will be converting the texual frequencies into number (number of days between purchases)

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
} 

df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

In [32]:
df["purchase_frequency_days"].unique()

array([ 14,   7, 365,  90,  30], dtype=int64)

In [33]:
df[["purchase_frequency_days","frequency_of_purchases"]].head(15)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly

In [34]:
df[["discount_applied","promo_code_used"]].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [35]:
# let's check of the "discount_applied" and "promo_code_used" contain the same information
(df["discount_applied"] == df["promo_code_used"]).all()

True

In [36]:
# that means they are the same values. we can just remove the promo_code_used column.

df = df.drop("promo_code_used", axis = 1)

In [37]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [38]:
# installing required libraries to connect our dataset with postgreSQL
!pip install psychopg2-binary sqlalchemy

ERROR: Could not find a version that satisfies the requirement psychopg2-binary (from versions: none)
ERROR: No matching distribution found for psychopg2-binary

In [39]:
import sys
print(sys.version)

3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]

In [40]:
import sys
!{sys.executable} -m pip install --upgrade pip setuptools wheel

Requirement already satisfied: pip in .\anaconda3\Lib\site-packages (26.0.1)
Requirement already satisfied: setuptools in .\anaconda3\Lib\site-packages (82.0.1)
Requirement already satisfied: wheel in .\anaconda3\Lib\site-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in .\anaconda3\Lib\site-packages (from wheel) (24.1)

In [41]:
import sys
!{sys.executable} -m pip install psycopg2-binary SQLAlchemy

Requirement already satisfied: psycopg2-binary in .\anaconda3\Lib\site-packages (2.9.11)
Requirement already satisfied: SQLAlchemy in .\anaconda3\Lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\Lib\site-packages (from SQLAlchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in .\anaconda3\Lib\site-packages (from SQLAlchemy) (3.0.1)

In [42]:
import psycopg2
import sqlalchemy

print("Everything installed correctly 🚀")

Everything installed correctly 🚀

In [43]:
from sqlalchemy import create_engine

In [45]:
# connecting postgreSQL with jupyter notebook

username = 'postgres'
password = 'Aman%4020024889'
host     = 'localhost'
port     = '5432'
database = 'customer_behavior'

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# STEP 2 : load datafrome into postgreSQL
table_name = 'customer'
df.to_sql(table_name, engine, if_exists = 'replace', index = False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.